# Generated by Django 4.2.10 on 2024-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('categories_tags_en', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
