# Generated by Django 4.2.10 on 2024-02-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_product_delete_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition_grade',
            field=models.CharField(max_length=10),
        ),
    ]
